#!/bin/sh

set -e

case "$1" in
	configure)
	;;

	triggered)
		update-m1n1 || echo "m1n1 update failed"
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
