#!/bin/sh

set -e

case "$1" in
	configure)
		echo Refresh gnome-42-2204 snap to asahi/stable channel
		snap refresh --channel asahi/stable --no-wait gnome-42-2204 || true
		echo Refresh mesa-2404 snap to asahi/stable channel
		snap refresh --channel asahi/stable --no-wait mesa-2404 || true

		# Update hwdb and regenrate initrd
		systemd-hwdb --usr update || true
		update-initramfs -kall -u
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
